server:
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customers?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
