server:
  port: 8010
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customers?currentSchema=public&serverTimezone=Asia/Calcutta
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: customer-service