server:
  port: 8081

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://product:product@product-db:27017/productdb

app:
  message: "Hello from Product Service (DEV)"
